$schema: https://json-schema.org/draft/2020-12/schema
meta:
  beaconId: string
  apiVersion: string
  returnedSchemas:
    - entityType: info
      schema: beacon-map-v2.0.0
response:
  $schema: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/configuration/beaconConfigurationSchema.json
  maturityAttributes:
    productionStatus: DEV
  securityAttributes:
    defaultGranularity: boolean
    securityLevels:
      - PUBLIC
      - REGISTERED
      - CONTROLLED
  entryTypes:
    dataset:
      id: dataset
      name: Dataset
      ontologyTermForThisType:
        id: NCIT:C47824
        label: Data set
      partOfSpecification: Beacon v2.0
      description: A Dataset is a collection of records, like rows in a database or
        cards in a cardholder.
      defaultSchema:
        id: datasetDefaultSchema
        name: Default schema for datasets
        referenceToSchemaDefinition: ./datasets/defaultSchema.json
        schemaVersion: v.2
      aCollectionOf:
        - id: exampleEntry
          name: Example entries
      endpoint: /datasets
      filteringTermsReference: ./datasets/filteringTerms.json
      additionallySupportedSchemas: []
    exampleEntry:
      id: exampleEntry
      name: Example Entry
      ontologyTermForThisType:
        id: NCIT:C20181
        label: Conceptual Entity
      partOfSpecification: Beacon v2.0
      description: A generic entry type to allow testing and playing with the specification.
      defaultSchema:
        id: ExampleEntryTypeDefaultschema
        name: Default schema for an example entries
        referenceToSchemaDefinition: ./exampleEntry/defaultSchema.json
        schemaVersion: v.2
      endpoint: ./exampleEntries
      filteringTermsReference: ./exampleEntry/filteringTerms.json
      additionallySupportedSchemas: []
info: {}
