site_name: Beacon v2 Documentation
site_description: 'Documentation for Beacon v2'
site_author: 'Michael Baudis, Manuel Rueda, Laureen Fromont & Beacon Developers'
copyright: '&copy; Copyright 2021-2023, Beacon v2 Documentation Contributors'
repo_name: 'beacon-v2'
repo_url: https://github.com/ga4gh-beacon/beacon-v2
edit_uri: edit/main/docs/

repo_framework_icon: " [:fontawesome-brands-github:](https://github.com/ga4gh-beacon/beacon-v2/tree/main/framework/src)"
repo_models_icon: " [:fontawesome-brands-github:](https://github.com/ga4gh-beacon/beacon-v2/tree/main/models/src)"

#<----------------------------- Navigation ----------------------------------->#

nav:
    - Introducing Beacon: 
        - Overview:
            - About Beacon: /
            - Beacon Types: beacon-flavours
            - Security: security
            - Beacon Networks: networks
        - FAQ: FAQ
        - Changes: bugs-changes-log
        - Beacon News &#8599;: https://beacon-project.io/news/
    - Using Beacons:
        - Data Discovery:
            - Genomic Queries: variant-queries
            - Phenotypes and More...: /filters/#using-filters-in-queries
        - Data Delivery:
            - Biosamples, Variants...: records
            - Data Handovers: handovers
            - REST API: rest-api
    - 'Creating Beacons':
        - Implementations Options: implementations-options
        - Implementation Examples:
            - Reference Implementation &#8599;: https://b2ri-documentation.readthedocs.io/en/latest/
            - Others: other-implementations
        - Standards Integration: formats-standards
        - Filters: filters
        - Beacon Components:
            - Framework: framework  
            - Beacon Data Model: models
            - Default Schemas:
               - Analyses: schemas-md/analyses_defaultSchema
               - Biosamples: schemas-md/biosamples_defaultSchema
               - Cohorts: schemas-md/cohorts_defaultSchema
               - Datasets: schemas-md/datasets_defaultSchema
               - Genomic Variations: schemas-md/genomicVariations_defaultSchema
               - Individuals: schemas-md/individuals_defaultSchema
               - Runs: schemas-md/runs_defaultSchema
            - Terms List: schemas-md/beacon_terms
    - Beacon Development:
        - How to Contribute: contribute
        - Repository and Branch Organization: code-organization
        - Github Repositories &#8599;: https://github.com/ga4gh-beacon/
    # - Download PDF: pdf/beacon.pdf

#<--------------------------- / Navigation ----------------------------------->#

extra_css: [css/theme_overrides.css]

plugins:
  - search
  # - with-pdf:
  #      author: Beacon API Development Team
  #      output_path: pdf/beacon.pdf
  - macros
  # - mermaid2

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.superfences
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: ga4gh-beacon
        repo: beacon-v2
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid   

theme:
    name: material
    palette:
        primary: teal
    logo: img/GA-logo.png
    favicon: img/ga4gh_circle.ico
    icon:
        repo: fontawesome/brands/github-alt 
    features:
        - content.tabs.link
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/genomebeacons
    - icon: fontawesome/brands/github 
      link: https://github.com/ga4gh-beacon

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
