site_name: Beacon v2 Documentation
site_description: 'Documentation for Beacon v2'
site_author: 'Manuel Rueda, Michael Baudis, Laureen Fromont & Beacon Developers'
copyright: '&copy; Copyright 2021-2022, Beacon v2 Documentation Contributors'
repo_name: 'beacon-v2'
repo_url: https://github.com/ga4gh-beacon/beacon-v2
edit_uri: edit/main/docs/

repo_framework_icon: " [:fontawesome-brands-github:](https://github.com/ga4gh-beacon/beacon-v2/tree/main/framework/src)"
repo_models_icon: " [:fontawesome-brands-github:](https://github.com/ga4gh-beacon/beacon-v2/tree/main/models/src)"

extra_css: [css/theme_overrides.css]

plugins:
  - search
  # - with-pdf:
  #      author: Beacon API Development Team
  #      output_path: pdf/beacon.pdf
  - macros
  - mermaid2

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.superfences
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: ga4gh-beacon
        repo: beacon-v2
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid   

nav:
    - Introduction: index.md
    - What is Beacon v2?: what-is-beacon-v2.md  
    # - Documentation Scopes: roles.md
    - Changes: bugs-changes-log.md
    - Beacon Types:
        - Beacon Flavours: beacon-flavours.md
        - Security: security.md
        - Networks: networks.md
    - 'Implement & Deploy a Beacon':
        - Implementations Options: implementations-options.md
#        - Tips for Implementers: _tips-for-implementers.md
        - Standards Integration: formats-standards.md
        - Filters: filters.md
        - Beacon Implementations:
            - Reference Implementation &#8599;: https://b2ri-documentation.readthedocs.io/en/latest/
            - Others: other-implementations.md
    - Beacon Components:
        - Framework: framework.md         
        - Models: 
           - Introduction: models.md
           - Default Schemas:
               - Analyses: schemas-md/analyses_defaultSchema.md
               - Biosamples: schemas-md/biosamples_defaultSchema.md
               - Cohorts: schemas-md/cohorts_defaultSchema.md
               - Datasets: schemas-md/datasets_defaultSchema.md
               - Genomic Variations: schemas-md/genomicVariations_defaultSchema.md
               - Individuals: schemas-md/individuals_defaultSchema.md
               - Runs: schemas-md/runs_defaultSchema.md    
           - Terms List: schemas-md/beacon_terms.md
#        - REST API: _rest-api.md
    - Querying Beacons:
        - Genomic Queries: variant-queries.md
        - Filters in Queries: filter-queries.md
    - External Links:
        - Beacon Project &#8599;: http://beacon-project.io
        - Github Repositories &#8599;: https://github.com/ga4gh-beacon/
#        - Read the Docs Version &#8599;: https://beacon-v2-unity.readthedocs.io/en/latest/
    # - Download PDF: pdf/beacon.pdf
    - Citation: citation.md

theme:
    name: material
    palette:
        primary: teal
    logo: img/GA-logo.png
    favicon: img/ga4gh_circle.ico
    icon:
        repo: fontawesome/brands/github-alt 
    features:
        - content.tabs.link
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/genomebeacons
    - icon: fontawesome/brands/github 
      link: https://github.com/ga4gh-beacon

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
